version: '3.8'

services:
  web:
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=flask:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - flask
  flask:
    build: flask
    environment: 
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      -  mongodb
  
  backend:
    build: backend
  
  mongodb:
    image: mongo:4.4.3

  mariadb:
    image: mariadb:10.6.4-focal
